name: Deploy to Coolify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Deploy to Coolify
        uses: coolify-cool/coolify-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authorization
          repo: "Elikanah890/student-management-system"  # Your repository
          branch: "main"  # The branch to deploy
